### ISSUE TITLE
wardend init should add precompile addresses in the genesis file

### ISSUE THREAD

**Issue by pitasi** [warden-protocol/wardenprotocol#1113]
If possible, it would be a nice addition to add our custom precompiles addresses to the genesis file created by `wardend init` (right now it only includes precompiles addresses bundled by evmos).

We're currently relying on some sed scripts inside our `justfile`, and even if it works, it feels a bit clunky.

**Comment by backsapc** [comment]
This doesn’t seem possible to do in a non-`clunky` way. According to the [Cosmos documentation](https://docs.cosmos.network/main/user/run-node/run-node#updating-some-default-settings), this is the idiomatic way to update the genesis. The issue comes from this piece of code: https://github.com/warden-protocol/wardenprotocol/blob/600acee356ee455354e6fabce38b90efafea19e1/cmd/wardend/cmd/commands.go#L49 

This function originates from `cosmos-sdk` and performs the `appGenState := mbm.DefaultGenesis(cdc)` operation internally. We would need to either add the ability to modify the default genesis in our fork of `cosmos-sdk` or fork `evmos` and make those changes there. Both solutions seem undesirable to me.  

Another possible solution would be to create a wrapper module for the `evm` module. The only change it would introduce is adding precompile addresses during the call to `DefaultGenesis`, while all other methods would simply proxy the raw behavior. In my opinion, I don’t think this solution is good either.  

@Pitasi  What do you think?

**Comment by pitasi** [comment]
hmm yeah it makes sense, looks like the sdk doesn't provide an easy way of tweaking the genesis file

it's up to the module to return the initial state, but we can't edit what x/evm is returning (we could actually, because the list of precompiles is a global var, but let's avoid doing it)
