### ISSUE TITLE
[Basic][Evmos]: Order contract

### ISSUE THREAD

**Issue by mn13** [warden-protocol/wardenprotocol#987]
Create IExecution interface with canExecute/execute.

Implement Order contract, that should implement IExecution.

canExecute() - gets price from Slinky and check if condition met
execute(nonce, gasPrice) - builds transaction and creates new sign request

self destructs after execution

**Comment by pitasi** [comment]
do we need the two different methods `canExecute` and `execute`?

if possible, i would have just one:
```
function execute() {
  if (!conditionsAreMet) {
    return;
  }
  buildTransaction();
  newSignRequest();
  selfDestruct();
}
```

are there any advantages in separating the two? i'm not a solidity dev so i might be missing something

**Comment by mn13** [comment]
I also thought about the only one, but as offchain scheduler will pay for each execute() call it's just cheaper to call canExecute() read-only method and then call execute() if conditions are met

**Comment by pitasi** [comment]
I see but if the code is something like:

```solidity
if (!conditionsAreMet()) {
  return;
}
doExpensiveWork();
```

it should be fine right? You only pay higher gas prices when the conditions are met.

Otherwise it becomes cumbersome to fetch some data, check if the data is good inside `conditionsAreMet()`, and then use the same data inside `doExpensiveWork()`. I don't know if I'm making myself clear 😁
