### ISSUE TITLE
[Basic][Worker]: Projects setup (Relayer)

### ISSUE THREAD

**Issue by mn13** [warden-protocol/wardenprotocol#989]
Create separate repositories for each worker.
Both would be node.js (ts) services.

**Comment by pitasi** [comment]
we could keep them inside this monorepo, unless there are benefits of having them elsewhere

**Comment by artur-abliazimov** [comment]
> we could keep them inside this monorepo, unless there are benefits of having them elsewhere

I think that we could follow the same approach as for the Fordefi keychain and just have a separate repository for it inside warden organization. We decided to keep them separately because they do not depend on each other. Also, we do not want the monorepo to grow with a lot of periphery services.

Let us know if you think we need to move it to the monorepo.

**Comment by pitasi** [comment]
> I think that we could follow the same approach as for the Fordefi keychain and just have a separate repository for it inside warden organization

Fordefi keychain is not operated by Warden Protocol and it's not inside this github organization though

Let's put all the services here in the monorepo, it's easier to coordinate all the issues and the work on them
